import { version } from './version';

export function header(oneLineDescription: string) {
    return `/* eslint-disable */
  /**
   * ${oneLineDescription}
   * 
   * THIS CODE IS AUTOMATICALLY GENERATED.
   * 
   * Generated by @locless/cli (${version}).
   * To regenerate, run \`npx locless deploy\`.
   */
  `;
}
